---
- name: Not permitting root login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin (no|yes)'
    line: 'PermitRootLogin no'
    backrefs: yes

- name: Reload SSH service
  ansible.builtin.systemd:
    name: ssh
    state: reloaded
